# appengine configuration file

# use the standard go runtime on appengine
runtime: go
api_version: go1
version: v1-beta

# url handlers
handlers:
# map /static(.*) to /static\1
- url: /
  script: _go_app
  secure: always
- url: /static
  static_dir: static
  application_readable: true
  secure: always
# map everything else to the backend
- url: /login
  script: _go_app
  secure: always
- url: /.*
  script: _go_app
  secure: always

# set environment variables
env_variables:
  GCLOUD_DATASET_ID: working-dog-data-dash
